[package]
name = "konoha"
description = "Flexible monolithic governance components for Starknet"
version = "0.4.0"
cairo-version = "2.6.3"

[dependencies]
starknet = ">=2.0.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.23.0" }


# can be fixed by doing import super::testing from tests
# [dev-dependencies] sadly can't use this because we have testing in src/

[lib]


# can be fixed by doing import super::testing from tests
[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.23.0" }

[lib]

[[target.starknet-contract]]

[scripts]
test = "snforge test"

[[tool.snforge.fork]]
name = "MAINNET"
url = "http://34.22.208.73:6060/v0_7"
block_id.tag = "Latest"

[[tool.snforge.fork]]
name = "SEPOLIA"
url = "http://34.22.208.73:6062/v0_7"
block_id.tag = "Latest"

RUST_BACKTRACE = 1
