[package]
name = "governance"
description = "A flexible monolithic governance contract, developed for use with Carmine Options AMM"
version = "0.2.0"
cairo-version = "2.1.1"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=1.1.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", branch = "war-in/1212-1175-switch-to-universal-sierra-compilation"}

[[target.starknet-contract]]

[[tool.snforge.fork]]
name = "MAINNET"
url = "https://limited-rpc.nethermind.io/mainnet-juno"
block_id.tag = "Latest"

[[tool.snforge.fork]]
name = "GOERLI"
url = "https://limited-rpc.nethermind.io/goerli-juno"
block_id.tag = "Latest"