[package]
name = "konoha"
description = "A flexible monolithic governance contract, developed for use with Carmine Options AMM"
version = "0.4.0"
cairo-version = "2.6.3"

[dependencies]
cubit = { git = "https://github.com/influenceth/cubit.git", commit = "62756082bf2555d7ab25c69d9c7bc30574ff1ce8" }
starknet = ">=2.0.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.20.1" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }


[lib]

[[target.starknet-contract]]

[[tool.snforge.fork]]
name = "MAINNET"
url = "http://34.22.208.73:6060/v0_7"
block_id.tag = "Latest"

[[tool.snforge.fork]]
name = "SEPOLIA"
url = "http://34.22.208.73:6062/v0_7"
block_id.tag = "Latest"

RUST_BACKTRACE = 1
