name: CI

on:
  push:
    paths:
      - '**.cairo'
      - '.github/'

env:
  SCARB_VERSION: 2.3.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Install Scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | bash -s -- -v $SCARB_VERSION
      - name: Check formatting
        run: scarb fmt --check
      - name: Build with scarb
        run: scarb build
